// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

/*
Package product is a generated protocol buffer package.

It is generated from these files:
	product.proto

It has these top-level messages:
	Product
	Image
	ProductList
*/
package product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	ID       string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Quantity uint64 `protobuf:"varint,3,opt,name=Quantity" json:"Quantity,omitempty"`
	Image    *Image `protobuf:"bytes,4,opt,name=Image" json:"Image,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Product) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type Image struct {
	URL  string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Image) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Image) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProductList struct {
	Products []*Product `protobuf:"bytes,1,rep,name=Products" json:"Products,omitempty"`
}

func (m *ProductList) Reset()                    { *m = ProductList{} }
func (m *ProductList) String() string            { return proto.CompactTextString(m) }
func (*ProductList) ProtoMessage()               {}
func (*ProductList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProductList) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Image)(nil), "product.Image")
	proto.RegisterType((*ProductList)(nil), "product.ProductList")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xf2, 0xb9,
	0xd8, 0x03, 0x20, 0x4c, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x26, 0x4f, 0x17, 0x21, 0x21, 0x2e, 0x16, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x08,
	0x98, 0x2d, 0x24, 0xc5, 0xc5, 0x11, 0x58, 0x9a, 0x98, 0x57, 0x92, 0x59, 0x52, 0x29, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x12, 0x04, 0xe7, 0x0b, 0xa9, 0x70, 0xb1, 0x7a, 0xe6, 0x26, 0xa6, 0xa7, 0x4a,
	0xb0, 0x28, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe9, 0xc1, 0xac, 0x04, 0x8b, 0x06, 0x41, 0x24, 0x95,
	0x74, 0xa1, 0xaa, 0x84, 0x04, 0xb8, 0x98, 0x43, 0x83, 0x7c, 0xa0, 0xf6, 0x81, 0x98, 0x20, 0x0b,
	0x5d, 0x12, 0x4b, 0x12, 0xc1, 0x16, 0xf2, 0x04, 0x81, 0xd9, 0x4a, 0xd6, 0x5c, 0xdc, 0x50, 0xf7,
	0xf9, 0x64, 0x16, 0x97, 0x08, 0xe9, 0x70, 0x71, 0x40, 0xb9, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a,
	0xdc, 0x46, 0x02, 0x70, 0x6b, 0xa0, 0x12, 0x41, 0x70, 0x15, 0x49, 0x6c, 0x60, 0xcf, 0x1a, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x7b, 0x4e, 0x6c, 0xfd, 0x00, 0x00, 0x00,
}
